using System.Xml.Serialization;

namespace XmlDownloader.Core.Models.SatModels.Complements.Payments.Pago10
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Este código fue generado por una herramienta.
    //     Versión de runtime:4.0.30319.42000
    //
    //     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
    //     se vuelve a generar el código.
    // </auto-generated>
    //------------------------------------------------------------------------------
    // 
    // Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
    // 


    /// <remarks/>
    [SerializableAttribute,
     XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos"),
     XmlRootAttribute(Namespace = "http://www.sat.gob.mx/Pagos", IsNullable = false)]
    public class Pagos
    {
        private PagosPago[] pagoField;

        private string versionField;

        public Pagos()
        {
            versionField = "1.0";
        }

        /// <remarks/>
        [XmlElementAttribute("Pago")]
        public PagosPago[] Pago
        {
            get { return pagoField; }
            set { pagoField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute]
        public string Version
        {
            get { return versionField; }
            set { versionField = value; }
        }
    }
}